### ISSUE TITLE
ideas to "improve" or "complete" hope.js

### ISSUE THREAD

**Issue by ghost** [poef/hope#7]
Hey!

I want to contribute to this repository I have 3 ideas: 
1. hope.js documentation with docsify on github pages. For example: ```hope-js-editor.github.io/docs/#```
2. add hash feature in hope.js, for example: SHA-256, MD5, SHA-384 etc.

*2.1 example without hash*
```
0-43:h3
45-139:p
116-126:a href="http://en.wikipedia.org/wiki/Ted_Nelson"
1185-1191:em
```

*2.2 example with hash*
```
6e27b0cf927d9ae2511eddc8954c04be3b83fc4e850d6b224c496e2161215dd0 #SHA256 for 0-43:h3
a560270543b776fc5e0682f018703692cd610f13f0958bd6c3f6eee0c568f995:p #SHA256 for 45-139
e6a68f0319b03281f937cfd3a61024fd href="http://en.wikipedia.org/wiki/Ted_Nelson" #md5 for 116-126:a
fac35b670725b95b8ec1e74986ad837f39adb4254d4920c43f95a4ec68d0a71e4760a9238413addd047c5f560c116306 #SHA384, 1185-1191:em
```

3. syntax highlight from hope.js to sublime-text.

```yaml

0-9:0-9 # case 1
a-z0-9:a-z0-9 # case 2

# case 3: symbol for comment is '#'

'0-9': '0-9' # case 4

'a-z0-9':'a-z0-9' # case 5
"a-z0-9":"a-z0-9" # case 6

"A-Z0-9":"A-Z0-9" # case 7
'A-Z0-9':'A-Z0-9' # case 8

"a-zA-Z0-9":"a-zA-Z0-9" # case 9 
'a-zA-Z0-9':'a-zA-Z0-9' # case 10 

# case 11: symbol for value can be '' or "" or value:value

start-value:end-value # case 12
'start-hash-type':'end-hash-type' # case 13, example: 'SHA-256:SHA-256', 'MD5:SHA-256', 'SHA-384:SHA-384' etc

"start-hash-type":"end-hash-type" # case 14, example: "SHA-256:SHA-256", "MD5:SHA-256", "SHA-384:SHA-384" etc
```
- ``a-zA-Z0-9``: regex just means that any lower case alphabet character from "a to z" is acceptable, as well as capital letters "A to Z" and the numbers "0 to 9" with "" or '' or without this "" and ''
- ``/\d+/g`` or ``[^0-9]``: regex that return just numbers  with "" or '' or without this "" and ''
- ``a-z``: regex just means that any lower case alphabet character from "a to z" is acceptable with "" or '' or without this "" and ''
- ``A-Z``: regex just means that any capital case alphabet character from "A to Z" is acceptable with "" or '' or without this "" and ''
- ``hash-type:hash-type:`` as SHA-256:SHA-256, MD5:SHA-256, SHA-384:SHA-384 etc  with "" or '' or without this "" and ''
- ``"hash-type":"hash-type"``: "SHA-256:SHA-256", "MD5:SHA-256", "SHA-384:SHA-384" etc  with ""
- ``'hash-type':'hash-type'``: 'SHA-256:SHA-256', 'MD5:SHA-256', 'SHA-384:SHA-384' etc  with ''
- ``'hash':'hash-type'``: 'MD5:SHA-256', 'MD5:SHA-384' etc  with ""
- ``'hash-type':'hash'``: 'SHA-256:MD5', 'SHA-384:MD5' etc  with ""
- ``"hash":"hash-type"``: "MD5:SHA-256", "MD5:SHA-384" etc  with ""
- ``"hash-type":'hash"``: "SHA-256:MD5", "SHA-384:MD5" etc  with ""

*If anyone likes these ideas I send the PR*

**Comment by poef** [comment]
Hi, thanks for taking a look at Hope. I'm intrigued by your hash idea, could you tell me a bit more about what you want to achieve with this?

I'm unsure why anyone would want a sublime-text syntax highlight module for hope annotations. There is no way to keep annotations and text in sync manually, so you should never have a need or want to open annotations in sublime.

As for the rest, have you taken a look at cobalt (https://github.com/poef/cobalt)? It is the successor to Hope, all new developments should probably go there. Any ideas about improving the documentation are welcome.

**Comment by ghost** [comment]
Hi poef.

> Hi, thanks for taking a look at Hope. 

thank you for feedback.

> I'm intrigued by your hash idea, could you tell me a bit more about what you want to achieve with this?

1. For my special use case, I'm thinking of using the hope.js version as a block protocol for versioning. Something similar to git, but applied or can be applied to text editors, web components and many online tools or online web applications as well. For example, here is a conceptual example of my idea:

![image](https://user-images.githubusercontent.com/111701513/215677601-fea14147-83df-406f-8277-425a7faebd34.png)

*As we can see in the image we have a git client that has an internal editor called tylr, this internal editor tylr implements the hope.js algorithm to version lines and columns of source code.*

2. So I was thinking of creating an api based on hope.js with hash

3. Also, things like git weren't thought of on the web, I'm thinking of creating a specification around hope.js as a diff file format on the web, where you can have a changelog of what has been processed, done, changed either by the server or the client side with website etc - because this has not yet been done in the proposal by WICG, W3C or any research bodies - *that is, it would be a way to collaborate, to help hope.js and web.*

4. In addition to these reasons I mentioned, there are two complementary ones. Ted Nelson's idea according to this technical standard was to use hash, as you can see in this link: [Infrastructure-Agnostic Hypertext](https://jakobib.github.io/hypertext2019/) and [DATA STRUCTURES OF XANADUÂ® PURPLE (informal)](https://xanadu.com/PurpData-D16.txt): *"1-Every document is uniquely and securely identified. 2-Every document can have secure access controls."*

5. I want to contribute with open source and I believe that this resource is something interesting, unique. It's not something you find in established publishers in the marketplace like ti - vscode, vim, notepad, sublimetext etc.

> I'm unsure why anyone would want a sublime-text syntax highlight module for hope annotations. There is no way to keep annotations and text in sync manually, so you should never have a need or want to open annotations in sublime.

1. My goal is to support syntax highlighting for sublimetext (text editor), that's all.

2. But another reason is that I would like hope.js to be a file format -  in addition to a js library for an editor -  a file format as well. That's why it's important to create syntax highlighting in sublimetext. 

3. Particularly, I've been using sublimetext for exactly 10 years and thought of offering support to the editor that I like and use the most.

4. Today there are standards like web components and block protocol. I think about creating a ".hope" or ".diff" format (I still have no idea what the file format is called). Anyway, this file format will be for web components and block protocol. 

> As for the rest, have you taken a look at cobalt (https://github.com/poef/cobalt)? It is the successor to Hope, all new developments should probably go there. 

1. I like the hope.js version, it's a small and lightweight version.

2. In my view, the way hope.js is, I can do content addressing and component for the block protocol and/or web-component. And also for the diff case I mentioned.

> Any ideas about improving the documentation are welcome.

I wanted hope.js documentation with docsify on github pages. For example: `hope-js-editor.github.io/docs/#`
